### ISSUE TITLE
How do I know if the user uses 1 finger or 2 fingers?

### ISSUE THREAD

**Issue by zenkog** [pskink/matrix_gesture_detector#14]
HI, thank you for the awesome package.
What I want to achieve is that I only want to Pan and Zoom whenever the user uses two fingers to do it. Because I have other needs for the single finger. So how can I detect whether it is a single finger touch or two fingers touch?

Thanks

**Comment by zenkog** [comment]
Finally I solved the problem by using Listener and embed the MatrixGestureDetector as its child. 
Then I can count how many points is touching the screen by using its onPointerDown callback. 

Hope this could help someone. Thanks

**Comment by alexsullivan114** [comment]
@zenkog I'd love to get a bit more info about how you solved this issue. Right now I'm using the `Listener` approach you outlined and setting `shouldTranslate` according to how many pointer events we've received, but I'm not sure how to actually act on a pan with a _single_ finger. Embedding another `GestureDetector` appears to throw off the gesture detector the library is using.

Any ideas?
