### ISSUE TITLE
widget outside MatrixGestureDetector is not response after got touch

### ISSUE THREAD

**Issue by lucreck** [pskink/matrix_gesture_detector#2]
<img width="1341" alt="Screen Shot 2019-09-25 at 21 32 22" src="https://user-images.githubusercontent.com/7540383/65613917-f05ff680-dfe0-11e9-884b-7d9971a4b988.png">

**Comment by lucreck** [comment]
I solved this by transform children not Stack

**Comment by sostenesgomes** [comment]
@lucreck whats was your solution?
