### ISSUE TITLE
One component at a time inside stack

### ISSUE THREAD

**Issue by Faiyyaz** [pskink/matrix_gesture_detector#6]
I want to move/scale/translate only the component which have been currently touched & rest other should stay at the same place. How can i achieve this?

Please find attached video representing the bug

[video.zip](https://github.com/pskink/matrix_gesture_detector/files/4049263/video.zip)

**Comment by pskink** [comment]
no bug reported

**Comment by Faiyyaz** [comment]
I m getting the bug

**Comment by ivtod** [comment]
Hi @Faiyyaz have you been able to do this?

**Comment by Faiyyaz** [comment]
No i have raised issue directly to flutter for support of fingercount in GestureDetector class so that we can implement rotate and pan separately
