### ISSUE TITLE
Resetting the matrix

### ISSUE THREAD

**Issue by ArthurDevv** [pskink/matrix_gesture_detector#8]
Is there a way to reset the matrix to `Matrix4.identity()`?

I'm currently trying to do this by setting the Matrix4 variable `matrix`, which is assigned to a `Transform` widget, to `setState(() => matrix = Matrix4.identity());` on the press of a button.

This seems to work but once I try to move the transform widget is jumps and starts it's transformation from the pre-reset state.

**Comment by pskink** [comment]
see 3 other parameters of onMatrixUpdate and static compose() method

**Comment by ArthurDevv** [comment]
I didn't really understand the reply but I worked around the problem by calling `Navigator.pushReplacement()` and passing in the same route. This solves my issue and then some.

You may explain how in more detail what you meant in the reply or go ahead and close the issue. Thanks for the  quick reply!

**Comment by pskink** [comment]
you are using only the first passed matrix which equals to tm * sm * rm -
if you want to set your matrix at any time you need to make that
multiplication on your own - that's why there is "compose" method - if
still not clear see it's implementation in the sources

**Comment by scopendo** [comment]
Hi @pskink – I didn't understand the reply either.  I think what both @ArthurDevv and I are trying to do is reset the transformed child back to it's initial rendered state.

With the code below, if I've zoomed the child, then the child reverts to looking correct after resetting the matrix, but the next gesture causes the child to render as it did prior to the reset.

```
  @override
  void initState() {
    super.initState();
    _initialMatrix = Matrix4.identity()..scale(0.9);
    _matrix = _initialMatrix;
  }

  @override
  Widget build(BuildContext context) {
    return MatrixGestureDetector(
      shouldRotate: false,
      onMatrixUpdate: (Matrix4 m, Matrix4 tm, Matrix4 sm, Matrix4 rm) {
        setState(() => _matrix = m);
      },
      child: Stack(
        children: <Widget>[
          LayoutBuilder(
            builder: (context, constraints) => Container(
              height: constraints.maxHeight,
              width: constraints.maxWidth,
              child: Center(
                child: Transform(
                  alignment: FractionalOffset.center,
                  transform: _matrix,
                  child: Stack(
                    children: <Widget>[
                      Image.asset("images/example.png"),
                      ..._otherWidgets(context),
                    ],
                  ),
                ),
              ),
            ),
          ),
          if (_matrix != _initialMatrix)
            Positioned(
              top: 30,
              right: 30,
              child: FloatingActionButton(
                child: Icon(Icons.undo),
                onPressed: () => setState(() => _matrix = _initialMatrix),
              ),
            ),
        ],
      ),
    );
  }
```

**Comment by pskink** [comment]
here is some demo on how to use "compose" method - now you can do whatever
you want with "matrix",
https://github.com/pskink/matrix_gesture_detector/blob/master/example/lib/transform_demo2.dart

**Comment by scopendo** [comment]
Thank you @pskink.  The code above now works fine after changing `onMatrixUpdate` to:

```
  onMatrixUpdate: (Matrix4 m, Matrix4 tm, Matrix4 sm, Matrix4 rm) {
    setState(() => _matrix = MatrixGestureDetector.compose(_matrix, tm, sm, rm));
  }
```

**Comment by ArthurDevv** [comment]
I can confirm that @scopendo's code solves my issue as well. Thanks for the assistance @pskink.
I'm going to close the issue now.
